### ISSUE TITLE
Dodanie nazwę podfolderu do nazwy plików w katalogu Roboczy 

### ISSUE THREAD

**Issue by mutipg** [openstreetmap-polska/ua_2022#8]
Może ktoś obeznany w skryptach hurtem pozmieniać nazwy plików w taki sposób, żeby nazwa podfolderu znalazła się w nazwie pliku? Po pobraniu pliku na dysk można się zagubić w podobnych nazwach :)

Proponuję, żeby w katalogu 'Roboczy' dla każdego pliku podmienić string ```JPT``` na ```<subfolder>_JPT```

Po zakończeniu skryptu spodziewam się takiego efektu:
przed:
```/Roboczy/apteki/woj_dolnoslaskie-pow_Jelenia_Gora-JPT_KOD_JE_0261.geojson```
po:
```/Roboczy/apteki/woj_dolnoslaskie-pow_Jelenia_Gora-apteki_JPT_KOD_JE_0261.geojson```

Dzięki!

**Comment by praszuk** [comment]
84f3faabed4cd006a520916ed4ea1c9463e6c7cb
Gotowe

**Comment by mutipg** [comment]
Dzięki, teraz jest wg mnie bardziej przyjaźnie dla usera :)
